version: ~> 1.0
dist: bionic
os: linux
language: python
cache: pip
services:
- postgresql
- mysql
python:
- 3.6
- 3.7
- 3.8
install: pip install -U codecov tox tox-travis
addons:
  postgresql: '10'
matrix:
  fast_finish: true
  include:
  - python: 3.6
    env: TOXENV=quality
before_script:
- export PIP_USE_MIRRORS=true
- export DJANGO_SETTINGS_MODULE=test_settings
- pg_lsclusters
# Postgres setup.
# Password is 'sortedm2m'
- psql -c "CREATE ROLE sortedm2m PASSWORD 'md5ba287bde612ca41b14776ec8f8dfdaa9' SUPERUSER
  CREATEDB CREATEROLE INHERIT LOGIN;" -U postgres
- psql -c "CREATE DATABASE sortedm2m OWNER sortedm2m;" -U postgres
# MySQL setup.
- echo "CREATE USER 'sortedm2m'@'localhost' IDENTIFIED BY 'sortedm2m';" | mysql -u
  root
- echo "GRANT ALL PRIVILEGES ON *.* TO 'sortedm2m'@'localhost' WITH GRANT OPTION;"
  | mysql -u root
script: tox -v
after_success: codecov
deploy:
  provider: pypi
  user: jazzband
  distributions: sdist bdist_wheel
  server: https://jazzband.co/projects/django-sortedm2m/upload
  password:
    secure: TfN/ENym4GrxYSno4FnrK9qXdceBEVU6k71OS2GYkiEmcwZMiAeXDivhddVgHswHEGxJnik6iu26EJUH4euXm0GZYI/1h0ihXQSWIfD8FnouhhlDpBmuW6BlvyDY7j9flfPDIc+LXseP3fel/ctCZibTdl5nHbaUIEGM6KTeRnE=
  on:
    tags: true
    repo: jazzband/django-sortedm2m
    python: 3.7
