language: python
cache: pip
dist: xenial
sudo: false
services:
  - postgresql
  - mysql

python:
  - pypy
  - 2.7
  - 3.4
  - 3.6
  - 3.7

matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=quality

install:
  - pip install -U codecov tox tox-travis

before_script:
  - export PIP_USE_MIRRORS=true
  - export DJANGO_SETTINGS_MODULE=test_settings
  - pg_lsclusters
  # Postgres setup.
  # Password is 'sortedm2m'
  - psql -c "CREATE ROLE sortedm2m PASSWORD 'md5ba287bde612ca41b14776ec8f8dfdaa9' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;" -U postgres
  - psql -c "CREATE DATABASE sortedm2m OWNER sortedm2m;" -U postgres
  # MySQL setup.
  - echo "CREATE USER 'sortedm2m'@'localhost' IDENTIFIED BY 'sortedm2m';" | mysql -u root
  - echo "GRANT ALL PRIVILEGES ON *.* TO 'sortedm2m'@'localhost' WITH GRANT OPTION;" | mysql -u root

script:
  - tox -v

after_success:
  codecov

deploy:
  provider: pypi
  user: gremu
  password:
    secure: jyiiGrkjiXhyc5rtvE6o/+z5XlkgQhzFX1LvgHlKMjk+HtRkRYm3jtUHxd0ZbuRNWwo6DbxmFWW7xiGc0uqrpRiH1vyuxA4FvTIO8fdxUmGwiTg8/IObuXAaXEVkfoxPZnLimKIBbFq6OXygwum32jfNCnEWiOu3hSfj1R5sRPw=
  on:
    tags: true
    repo: jazzband/django-sortedm2m
    condition: "$TOXENV = py36-dj22"
